version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: my-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_TIMEOUT_SEC=10
    depends_on:
      - mongo
volumes:
  mongo-data:          
